### ISSUE TITLE
Install

### ISSUE THREAD

**Issue by rbiswas-mirp** [witsec/mobirise-white-label#1]
How to install it?

**Comment by ExpertSunny** [comment]
Zip the folder. Change .zip to .mbrext and import it in Mobirise.

**Comment by rbiswas-mirp** [comment]
thanks!

**Comment by rbiswas-mirp** [comment]
it says error while installing

**Comment by rbiswas-mirp** [comment]
installed successfully...now how to use it?

**Comment by rbiswas-mirp** [comment]
installation error is there...unable to install..please help

**Comment by rbiswas-mirp** [comment]
Please help

**Comment by rbiswas-mirp** [comment]
Hello please help!

**Comment by witsec** [comment]
Sorry for my belated reply, I didn't get a notification from this earlier.

Anyway, when it's installed, you go to "Menu > Site > Site Settings", there you can flip the switch to enable "white label".

What installation error are you getting?
And what version of Mobirise do you have installed?

**Comment by ExpertSunny** [comment]
I too had faced problems installing it but I figured it out. Create a zip file with app.js, params.json, splash.html, splash.jpg, thumbnail.png inside it. Change the extension of the zip file by renaming it to whitelabel.mbrext . If you still face difficulty, I have uploaded it to my Drive. You can download it from here(https://drive.google.com/open?id=1N24AtOdQVOA4FrCuHFJCbR6B6FLlYx0Q).
And Thanks to Witsec for the amazing extension!

**Comment by witsec** [comment]
I've added a little [README](https://github.com/witsec/mobirise-white-label) to this repository. This contains a link to my website, where you can find all my Mobirise extensions.
