### ISSUE TITLE
index , js and css have name mobirise

### ISSUE THREAD

**Issue by deejay87** [witsec/mobirise-white-label#4]
Hi
Dont know if this can be change directly when export

Into the index.html
```
<link rel="preload" as="style" href="assets/mobirise/css/mbr-additional.css"><link rel="stylesheet" href="assets/mobirise/css/mbr-additional.css" type="text/css">
```
And in this folder css and js with 
```
/*!
 * Mobirise v4 theme (https://mobirise.com/)
 * Copyright 2017 Mobirise
 */
```
thanks :)

**Comment by witsec** [comment]
Some things can't be changed on export. Other things I don't think should be changed.

For example, if I'd use Wordpress and some theme, would I hide the fact I'm using Wordpress by renaming directories and files? And would I hide who made the theme? I personally wouldn't.

If that's what you're after though, take a look at [Mobiclean](https://richosoft.mobi/mobiclean-from-richosoft-software.html). It's not free though.

**Comment by deejay87** [comment]
Indeed, I thought it was a complete cleaning, but this does not interfere absolutely and it is completely legitimate to leave in the state
Anyway thank you for all the addons :)
